name: Supabase Keep-Alive
on:
  schedule:
    - cron: "0 6 */3 * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase
        run: |
<<<<<<< HEAD
          curl -v -X GET "https://dyhajmtfkjtwkijhptjx.supabase.co/rest/v1/" \
            -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}"
=======
          curl -sf -X GET "https://dyhajmtfkjtwkijhptjx.supabase.co/rest/v1/" \
            -H "apikey: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}"
>>>>>>> 36fcb54 (Keep Alive Added)
